
settings:
  anchor: true
  color: true
  default: true
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
  lockfile: false

formatter: "markdown table"

output:
  # TODO: Make this support multiple module READMEs
  file: azurerm-conditional-access/README.md
  mode: inject

sections:
  show:
    - providers
    - inputs
    - outputs

sort:
  enabled: true
  by: required
