name: Validate

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install terraform and dependencies
      uses: alphagov/gds-github-workflows/terraform/deps@47ffdc3007aef6b4857115b97135ed8b7b7c18ca # v0.1.7
      with:
        terraform-docs-version: 'v0.20.0'
        terraform-docs-sha256: |
          2fdd81b8d21ff1498cd559af0dcc5d155835f84600db06d3923e217124fc735a
          35b2e6846268841484e6eea7d00d7dfe2c94b4725e52cfe19aa6c26a86c32edc

    - name: Run pre-commit
      uses: alphagov/gds-github-workflows/pre-commit@0887a2b5712cf4e192ca4340f7c494606672a6bf # v0.1.6
