name: Validate

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install terraform and dependencies
      uses: alphagov/gds-github-workflows/terraform/deps@c055830bd101a2a3b9d08fba7777473c69a3af49 # v0.1.4

    - name: Run pre-commit
      uses: alphagov/gds-github-workflows/pre-commit@c055830bd101a2a3b9d08fba7777473c69a3af49 # v0.1.3
